# Generated by Django 5.2.4 on 2025-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_create_simproviders'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Optional discount (%) to apply to all its plans', null=True),
        ),
    ]
