# Generated by Django 5.2.4 on 2025-08-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plans_discount_price_provider_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='provider',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discount (%) to apply to all its plans', max_digits=5, null=True),
        ),
    ]
