# Generated by Django 5.2.4 on 2025-08-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_plans_discount_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='discount_percentage',
            new_name='discount_percentage_decimal',
        ),
    ]
