# Generated by Django 5.2.4 on 2025-08-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_rename_discount_percentage_provider_discount_percentage_decimal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='discount_percentage_decimal',
            new_name='discount_percentage',
        ),
    ]
