# Generated by Django 5.2.4 on 2025-08-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_rename_discount_percentage_decimal_provider_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='point_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Point value used for calculating discount', max_digits=10, null=True),
        ),
    ]
