# Generated by Django 5.2.4 on 2025-08-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_provider_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_banners/'),
        ),
    ]
