# Generated by Django 5.2.4 on 2025-07-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_bio_alter_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sim_provider',
            field=models.CharField(blank=True, choices=[('Airtel', 'Airtel'), ('Jio', 'Jio'), ('Vi', 'Vi'), ('BSNL', 'BSNL')], max_length=20, null=True),
        ),
    ]
