# Generated by Django 5.2.4 on 2025-07-24 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_sim_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_sms', models.BooleanField(default=True)),
                ('recharge_successful', models.BooleanField(default=True)),
                ('recharge_failed', models.BooleanField(default=True)),
                ('new_user_registered', models.BooleanField(default=True)),
                ('low_balance', models.BooleanField(default=True)),
                ('maintenance_schedule', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
