# Generated by Django 5.2.4 on 2025-07-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notificationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
