# Generated by Django 5.2.4 on 2025-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sim_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
