# Generated by Django 5.2.4 on 2025-07-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_simproviders'),
        ('accounts', '0008_delete_notificationsettings'),
    ]

    operations = [
    ]
