# Generated by Django 5.2.4 on 2025-07-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_sim_provider'),
        ('plans', '0002_create_simproviders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sim_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.provider'),
        ),
    ]
